# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Working/Basys-3-Master.xdc

# Block Designs: bd/MicroBlaze_GPIO/MicroBlaze_GPIO.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO || ORIG_REF_NAME==MicroBlaze_GPIO} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_microblaze_0_0/MicroBlaze_GPIO_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_microblaze_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_dlmb_v10_0/MicroBlaze_GPIO_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_dlmb_v10_0 || ORIG_REF_NAME==MicroBlaze_GPIO_dlmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_ilmb_v10_0/MicroBlaze_GPIO_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_ilmb_v10_0 || ORIG_REF_NAME==MicroBlaze_GPIO_ilmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_dlmb_bram_if_cntlr_0/MicroBlaze_GPIO_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlaze_GPIO_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_ilmb_bram_if_cntlr_0/MicroBlaze_GPIO_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlaze_GPIO_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_lmb_bram_0/MicroBlaze_GPIO_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_lmb_bram_0 || ORIG_REF_NAME==MicroBlaze_GPIO_lmb_bram_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_mdm_1_0/MicroBlaze_GPIO_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_mdm_1_0 || ORIG_REF_NAME==MicroBlaze_GPIO_mdm_1_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_clk_wiz_1_0/MicroBlaze_GPIO_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_clk_wiz_1_0 || ORIG_REF_NAME==MicroBlaze_GPIO_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_rst_clk_wiz_1_100M_0/MicroBlaze_GPIO_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MicroBlaze_GPIO_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_axi_gpio_0_0/MicroBlaze_GPIO_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_axi_gpio_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_axi_uartlite_0_0/MicroBlaze_GPIO_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_xbar_0/MicroBlaze_GPIO_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_xbar_0 || ORIG_REF_NAME==MicroBlaze_GPIO_xbar_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_microblaze_0_axi_periph_0/MicroBlaze_GPIO_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroBlaze_GPIO_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_gpio_0_0/MicroBlaze_GPIO_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_gpio_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_gpio_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_gpio_1_0/MicroBlaze_GPIO_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_gpio_1_0 || ORIG_REF_NAME==MicroBlaze_GPIO_gpio_1_0} -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_microblaze_0_0/MicroBlaze_GPIO_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_microblaze_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_microblaze_0_0/MicroBlaze_GPIO_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_lmb_bram_0/MicroBlaze_GPIO_lmb_bram_0_ooc.xdc

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_mdm_1_0/MicroBlaze_GPIO_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_mdm_1_0 || ORIG_REF_NAME==MicroBlaze_GPIO_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_mdm_1_0/MicroBlaze_GPIO_mdm_1_0_ooc_trace.xdc

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_clk_wiz_1_0/MicroBlaze_GPIO_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_clk_wiz_1_0 || ORIG_REF_NAME==MicroBlaze_GPIO_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_clk_wiz_1_0/MicroBlaze_GPIO_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_clk_wiz_1_0 || ORIG_REF_NAME==MicroBlaze_GPIO_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_clk_wiz_1_0/MicroBlaze_GPIO_clk_wiz_1_0_ooc.xdc

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_rst_clk_wiz_1_100M_0/MicroBlaze_GPIO_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MicroBlaze_GPIO_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_rst_clk_wiz_1_100M_0/MicroBlaze_GPIO_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MicroBlaze_GPIO_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_axi_gpio_0_0/MicroBlaze_GPIO_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_axi_gpio_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_axi_gpio_0_0/MicroBlaze_GPIO_axi_gpio_0_0_ooc.xdc

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_axi_gpio_0_0/MicroBlaze_GPIO_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_axi_gpio_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_axi_uartlite_0_0/MicroBlaze_GPIO_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_axi_uartlite_0_0/MicroBlaze_GPIO_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/ip/MicroBlaze_GPIO_axi_uartlite_0_0/MicroBlaze_GPIO_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_GPIO_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlaze_GPIO_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Working/FPGA_Harman_sys_verilog_improve/sys_ver_imp_25_11_03/sys_ver_imp_25_11_03.gen/sources_1/bd/MicroBlaze_GPIO/MicroBlaze_GPIO_ooc.xdc
